### PR TITLE
Add support for params via yaml file

### PR DESCRIPTION
**Pull request by barnsnake351**
Thanks for putting this tool together, I took a stab at adding support for params via a yaml file.  This is my first stab at Rust, so let me know if anything could be tweaked.

Thanks again,
Brian

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Thank you for the PR! This feature has been requested a few times (tracking issue is #7) so it will be great to finally get this in. I think I'd like to move the bulk of the logic for this into the ktmpl library, so that the executable (`main.rs`) only loads the contents of the file as a string and the string to `ParameterValues` conversion happens inside the library. I think it's probably best to keep things simple and not support nested values in the parameters file, as well.

I just landed another new feature, so I'm afraid you'll have to rebase your code, though I think the conflicts should be easy to resolve.

**Comment by barnsnake351** [comment]
Ok, great. I'll pull in your change, refactor a bit and get back to you hopefully by next week.

**Comment by jimmycuadra** [comment]
No rush! Another thing I forgot is that we should explicitly mention in the docs what the effect of supplying multiple parameter files is: that values in later files override ones in previous files when there's a conflict.

**Comment by barnsnake351** [comment]
I have refactored this a bit and added a test case. I also went ahead and re-ordered the input chain such that parameters are read from any files before they are read from the command line, this should have the effect of allowing any parameters passed via the command line to have precedence and override anything passed via a file.

**Comment by jimmycuadra** [comment]
Thank you very much for the contribution!

**Pull request merged**
