### PR TITLE
Adds a dockerfile for ktmpl

### PR DESCRIPTION
**Pull request by kri5**
This allow to build a dockerfile with ktmpl inside it
and running the container will run ktmpl

### CODE REVIEW

**Comment by jimmycuadra** [comment]
What is your intended purpose for the resulting Docker image?

**Comment by kri5** [comment]
It can be used as the application itself, or to be able to use ktmpl in a clean environment, for example in the case of CI.

You just have to mount your workspace into the ktmpl dockerfile and generates files.

There could be many uses for a docker image.

**Comment by jimmycuadra** [comment]
Ah. In that case, I'd prefer to use the scratch base image and put a statically compiled ktmpl into it. I have a good way of doing this already, so I will leave this PR open to remind me add one for this project. Thanks!

**Comment by kri5** [comment]
Great! Looking forward for your docker image.

**Comment by jimmycuadra** [comment]
https://hub.docker.com/r/inquicker/ktmpl/

**Pull request closed without merging**
